# PORTA DO SERVICO
server:
  port: 8087

#CONGIURAÇÃO DO SPRING
spring:
 # SERVICE REGISTRE - NOME DO SERVICO
  application:
    name: ead-authuser-service

  #DATABASE
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
      ansi:
          enabled: Always

# LOGGING
logging:
    level:
        com.ead: TRACE
        root: INFO
        org.springframework.web: DEBUG
        org.hibernate: INFO

# ENDEREÇO DE ACESSO AO SERVICO
ead:
    api:
        url:
            course: 'http://ead-course-service'


# ENDERECO SERVICEREGISTRE
eureka:
    client:
        serviceUrl:
            defaultZone: 'http://localhost:8761/eureka'
    instance:
        hostname: localhost