# PORTA DO SERVICO
server:
  port: 8082
#CONGIURAÇÃO DO SPRING
spring:
  # SERVICE REGISTRE - NOME DO SERVICO
  application:
    name: ead-course-service

  #DATABASE
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# LOGGING
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

# ENDEREÇO DE ACESSO AO SERVICO
ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'

# ENDERECO SERVICEREGISTRE
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost